### ISSUE TITLE
Add latex-makefile project as a build tool

### ISSUE THREAD

**Issue by alejandrogallo** [egeerardyn/awesome-LaTeX#5]
Hi,

I wanted to ask if it is possible to add my regularly maintained [Makefile](https://github.com/alejandrogallo/latex-makefile) for latex. Since it is not so widespread as latexmk of course I'd understand if you guys are weary of it.

Cheers

**Comment by egeerardyn** [comment]
Hi, sorry for the late response. Feel free to file PR for adding your makefile :smile:, but please do specify in what respect it is awesome (i.e. "better" than latexmk/arara/...)

**Comment by alejandrogallo** [comment]
Hi,

I just made the PR, I was quite conservative in what concerns the awesomeness of the Makefile, I don't want to oversell it since latexmk and arara are great projects, I just think it strives to be as general as possible and without dependencies, so one can just drop the Makefile in a random project and hit make.

Thx
