### ISSUE TITLE
add tinytex

### ISSUE THREAD

**Issue by DanielRuf** [egeerardyn/awesome-LaTeX#64]
I think tinytex (like tectonic) is a great solution to use latex on more devices and in more environments where a full LaTeX distribution is not required or needed.

https://github.com/rstudio/tinytex

**Comment by egeerardyn** [comment]
Certainly a nice addition (and the same holds for #63, #62 and #61 ), please open up a pull request with those added in the relevant section or add a new section where relevant (can even be in the same PR as far as I'm concerned): any description you write will be better than what I can come up with without practical experience with the projects :-)
